<?php
declare(strict_types=1);

namespace Aetherfall\Services;

use Aetherfall\Formula\FormulaEngine;
use PDO;
use RuntimeException;

/** Resolves class resources through the owning class relation, never by name or array position. */
final class ClassResourceService
{
    public function __construct(private PDO $pdo) { $this->ensureSchema(); }

    public function definitionsForCharacter(int $characterId): array
    {
        $sql = "SELECT cc.id character_class_id,cc.role,cc.class_id,cc.class_level,c.name class_name,cr.*
                FROM character_classes cc JOIN classes c ON c.id=cc.class_id
                JOIN class_resources cr ON cr.class_id=cc.class_id WHERE cc.character_id=?
                ORDER BY CASE cc.role WHEN 'primary' THEN 1 WHEN 'secondary_1' THEN 2 ELSE 3 END,cr.resource_id";
        $s=$this->pdo->prepare($sql);$s->execute([$characterId]);$out=[];
        foreach($s->fetchAll() as $row){$row['maximum']=$this->resolveMaximum($row,(int)$row['class_level']);$row['current']=$this->currentForClass((int)$row['character_class_id'],(string)$row['resource_id'],$row['maximum']);$out[]=$row;}
        return $out;
    }

    /** Reconcile all states belonging to the current class relations of a character. */
    public function reconcileCharacterClassResources(int $characterId): array
    {
        $report=['character_id'=>$characterId,'relations'=>0,'correct'=>0,'created'=>0,'removed'=>0,'clamped'=>0,'warnings'=>[]];
        $relations=$this->pdo->prepare('SELECT id,class_id,class_level,role FROM character_classes WHERE character_id=?');$relations->execute([$characterId]);$relationRows=$relations->fetchAll();$report['relations']=count($relationRows);
        $seen=[];
        foreach($relationRows as $relation){
            $classId=(string)$relation['class_id'];$relationId=(int)$relation['id'];$seen[$relationId]=true;$definitions=$this->definitionsForClass($classId,(int)$relation['class_level']);$expected=[];foreach($definitions as $definition)$expected[(string)$definition['resource_id']]=$definition;
            $state=$this->pdo->prepare('SELECT id,class_resource_id,current_value FROM character_class_resources WHERE character_class_id=?');$state->execute([$relationId]);
            foreach($state->fetchAll() as $row){$rid=(string)$row['class_resource_id'];if(!isset($expected[$rid])){$this->pdo->prepare('DELETE FROM character_class_resources WHERE id=?')->execute([(int)$row['id']]);$report['removed']++;continue;}$max=$expected[$rid]['maximum'];$current=$this->clamp((float)$row['current_value'],$max);if($current!==(float)$row['current_value']){$this->pdo->prepare('UPDATE character_class_resources SET current_value=? WHERE id=?')->execute([$current,(int)$row['id']]);$report['clamped']++;}$report['correct']++;}
            foreach($expected as $rid=>$definition){$check=$this->pdo->prepare('SELECT id FROM character_class_resources WHERE character_class_id=? AND class_resource_id=?');$check->execute([$relationId,$rid]);if($check->fetchColumn()!==false)continue;$this->pdo->prepare('INSERT INTO character_class_resources (character_class_id,class_resource_id,current_value) VALUES (?,?,?)')->execute([$relationId,$rid,$this->resolveStart($definition,$definition['maximum'])]);$report['created']++;}
        }
        try {
            if($seen){$placeholders=implode(',',array_fill(0,count($seen),'?'));$staleDelete=$this->pdo->prepare("DELETE ccr FROM character_class_resources ccr LEFT JOIN character_classes cc ON cc.id=ccr.character_class_id WHERE cc.id IS NULL OR (cc.character_id=? AND ccr.character_class_id NOT IN ({$placeholders}))");$staleDelete->execute([$characterId,...array_keys($seen)]);$report['removed']+=(int)$staleDelete->rowCount();}
            else{$staleDelete=$this->pdo->prepare('DELETE ccr FROM character_class_resources ccr JOIN character_classes cc ON cc.id=ccr.character_class_id WHERE cc.character_id=?');$staleDelete->execute([$characterId]);$report['removed']+=(int)$staleDelete->rowCount();}
        } catch (\Throwable) {
            $stale=$this->pdo->prepare('SELECT ccr.id FROM character_class_resources ccr LEFT JOIN character_classes cc ON cc.id=ccr.character_class_id WHERE cc.id IS NULL OR (cc.character_id=? AND (?=0 OR ccr.character_class_id NOT IN ('.($seen?implode(',',array_fill(0,count($seen),'?')):'0').')))');
            $stale->execute($seen?[$characterId,0,...array_keys($seen)]:[$characterId,0]);$delete=$this->pdo->prepare('DELETE FROM character_class_resources WHERE id=?');foreach($stale->fetchAll() as $row){$delete->execute([(int)$row['id']]);$report['removed']++;}
        }
        return $report;
    }

    public function ensureCharacterStates(int $characterId): void { $this->reconcileCharacterClassResources($characterId); }

    public function setCharacterCurrent(int $characterId,string $resourceId,float $value,?string $classId=null,?int $characterClassId=null): array
    { $this->ensureCharacterStates($characterId);if($characterClassId!==null)return$this->setCharacterCurrentForClass($characterId,$characterClassId,$resourceId,$value);$candidates=$this->characterResourceCandidates($characterId,$resourceId,$classId);if(count($candidates)!==1){$label=$candidates[0]['name']??$resourceId;throw new RuntimeException(count($candidates)>1?"Klassenressource '{$label}' ist ohne Klassenbezug nicht eindeutig.":"Klassenressource '{$label}' ist diesem Charakter nicht zugeordnet.");}return$this->setCharacterCurrentForClass($characterId,(int)$candidates[0]['character_class_id'],$resourceId,$value); }

    public function setCharacterCurrentForClass(int $characterId,int $characterClassId,string $resourceId,float $value): array
    { $s=$this->pdo->prepare('SELECT cc.id,cc.class_id,cc.class_level,cr.* FROM character_classes cc JOIN class_resources cr ON cr.class_id=cc.class_id AND cr.resource_id=? WHERE cc.id=? AND cc.character_id=?');$s->execute([$resourceId,$characterClassId,$characterId]);$row=$s->fetch();if(!$row)throw new RuntimeException("Klassenressource '{$resourceId}' ist dieser Klasseninstanz nicht zugeordnet.");$max=$this->resolveMaximum($row,(int)$row['class_level']);$value=$this->clamp($value,$max);$this->pdo->prepare('UPDATE character_class_resources SET current_value=? WHERE character_class_id=? AND class_resource_id=?')->execute([$value,$characterClassId,$resourceId]);return['resource_id'=>$resourceId,'character_class_id'=>$characterClassId,'current'=>$value,'maximum'=>$max]; }

    public function createCombatSnapshot(int $participantId,int $characterId): void { $this->reconcileCombatParticipantResources($participantId,$characterId); }

    /** Repair an existing character participant while preserving only exact relation/resource states. */
    public function reconcileCombatParticipantResources(int $participantId,?int $characterId=null): array
    {
        $query=$this->pdo->prepare('SELECT participant_type,reference_id FROM combat_participants WHERE id=?');$query->execute([$participantId]);$participant=$query->fetch();if(!$participant||$participant['participant_type']!=='character')return['participant_id'=>$participantId,'created'=>0,'removed'=>0,'updated'=>0,'warnings'=>['Kein Charakter-Teilnehmer.']];
        $characterId=$characterId??(int)$participant['reference_id'];$this->reconcileCharacterClassResources($characterId);$expected=$this->definitionsForCharacter($characterId);$byKey=[];$byRid=[];foreach($expected as $row){$key=(int)$row['character_class_id'].'|'.(string)$row['resource_id'];$byKey[$key]=$row;$byRid[(string)$row['resource_id']][]=$row;}
        $s=$this->pdo->prepare('SELECT cpr.*,cc.character_id,cc.class_id relation_class_id FROM combat_participant_resources cpr LEFT JOIN character_classes cc ON cc.id=cpr.character_class_id WHERE cpr.combat_participant_id=?');$s->execute([$participantId]);$used=[];$report=['participant_id'=>$participantId,'created'=>0,'removed'=>0,'updated'=>0,'warnings'=>[]];
        foreach($s->fetchAll() as $row){$relationId=$row['character_class_id']===null?null:(int)$row['character_class_id'];$key=$relationId===null?null:$relationId.'|'.(string)$row['class_resource_id'];$target=$key!==null?($byKey[$key]??null):null;if(!$target&&$relationId===null&&count($byRid[(string)$row['class_resource_id']]??[])===1){$target=$byRid[(string)$row['class_resource_id']][0];$key=(int)$target['character_class_id'].'|'.(string)$target['resource_id'];}if(!$target||isset($used[$key])){$this->pdo->prepare('DELETE FROM combat_participant_resources WHERE id=?')->execute([(int)$row['id']]);$report['removed']++;continue;}$used[$key]=true;$current=$this->clamp((float)$row['current_value'],$target['maximum']);$maxChanged=$target['maximum']===null?$row['max_value_snapshot']!==null:($row['max_value_snapshot']===null||(float)$row['max_value_snapshot']!==(float)$target['maximum']);$changed=$relationId!==(int)$target['character_class_id']||(string)$row['class_resource_id']!==(string)$target['resource_id']||$maxChanged||(float)$row['current_value']!==$current;if($changed){$this->pdo->prepare('UPDATE combat_participant_resources SET character_class_id=?,class_resource_id=?,current_value=?,max_value_snapshot=? WHERE id=?')->execute([(int)$target['character_class_id'],$target['resource_id'],$current,$target['maximum'],(int)$row['id']]);$report['updated']++;}}
        $insert=$this->pdo->prepare('INSERT INTO combat_participant_resources (combat_participant_id,character_class_id,class_resource_id,current_value,max_value_snapshot) VALUES (?,?,?,?,?)');foreach($expected as $row){$key=(int)$row['character_class_id'].'|'.(string)$row['resource_id'];if(isset($used[$key]))continue;$insert->execute([$participantId,(int)$row['character_class_id'],$row['resource_id'],(float)$row['current'],$row['maximum']]);$report['created']++;}return$report;
    }

    public function statesForParticipant(int $participantId): array
    { try{$this->reconcileCombatParticipantResources($participantId);$s=$this->pdo->prepare("SELECT cpr.*,cr.name,cr.class_id,cc.role,c.name class_name,cc.class_level FROM combat_participant_resources cpr JOIN character_classes cc ON cc.id=cpr.character_class_id JOIN class_resources cr ON cr.class_id=cc.class_id AND cr.resource_id=cpr.class_resource_id LEFT JOIN classes c ON c.id=cc.class_id WHERE cpr.combat_participant_id=? ORDER BY CASE cc.role WHEN 'primary' THEN 1 WHEN 'secondary_1' THEN 2 ELSE 3 END,cpr.id");$s->execute([$participantId]);return$s->fetchAll();}catch(\Throwable){return[];} }

    public function setCombatCurrent(int $participantId,string $resourceId,float $value,?string $classId=null,?int $characterClassId=null): array
    { $row=$this->findCombatResource($participantId,$resourceId,$classId,$characterClassId);$value=$this->clamp($value,$row['max_value_snapshot']);$this->pdo->prepare('UPDATE combat_participant_resources SET current_value=? WHERE id=?')->execute([$value,(int)$row['id']]);return['resource_id'=>$resourceId,'character_class_id'=>(int)$row['character_class_id'],'current'=>$value,'maximum'=>$row['max_value_snapshot']]; }

    public function spend(int $participantId,string $executionId,string $resourceId,float $amount,?string $classId=null): bool
    { if($amount<=0)return false;$this->pdo->beginTransaction();try{$row=$this->findCombatResource($participantId,$resourceId,$classId);$check=$this->pdo->prepare('SELECT id FROM combat_resource_transactions WHERE combat_participant_id=? AND execution_id=? AND class_resource_id=? AND (character_class_id=? OR character_class_id IS NULL)');$check->execute([$participantId,$executionId,$resourceId,(int)$row['character_class_id']]);if($check->fetchColumn()!==false){$this->pdo->commit();return false;}$lock=$this->pdo->getAttribute(PDO::ATTR_DRIVER_NAME)==='mysql'?' FOR UPDATE':'';$s=$this->pdo->prepare('SELECT current_value FROM combat_participant_resources WHERE id=?'.$lock);$s->execute([(int)$row['id']]);$current=$s->fetchColumn();if($current===false||((float)$current<$amount))throw new RuntimeException("Nicht genug Klassenressource '{$row['name']}' vorhanden.");$this->pdo->prepare('UPDATE combat_participant_resources SET current_value=current_value-? WHERE id=?')->execute([$amount,(int)$row['id']]);$this->insertTransaction($participantId,$executionId,$resourceId,-$amount,(int)$row['character_class_id']);$this->pdo->commit();return true;}catch(\Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw$e;} }

    public function gain(int $participantId,string $executionId,string $resourceId,float $amount,?string $classId=null): bool
    { if($amount<=0)return false;$this->pdo->beginTransaction();try{$row=$this->findCombatResource($participantId,$resourceId,$classId);$check=$this->pdo->prepare('SELECT id FROM combat_resource_transactions WHERE combat_participant_id=? AND execution_id=? AND class_resource_id=? AND (character_class_id=? OR character_class_id IS NULL)');$check->execute([$participantId,$executionId,$resourceId,(int)$row['character_class_id']]);if($check->fetchColumn()!==false){$this->pdo->commit();return false;}$lock=$this->pdo->getAttribute(PDO::ATTR_DRIVER_NAME)==='mysql'?' FOR UPDATE':'';$s=$this->pdo->prepare('SELECT current_value,max_value_snapshot FROM combat_participant_resources WHERE id=?'.$lock);$s->execute([(int)$row['id']]);$state=$s->fetch();if(!$state)throw new RuntimeException("Kampfressource '{$row['name']}' ist für diese Klasseninstanz im Kampf nicht verfügbar.");$value=(float)$state['current_value']+$amount;if($state['max_value_snapshot']!==null)$value=min($value,(float)$state['max_value_snapshot']);$this->pdo->prepare('UPDATE combat_participant_resources SET current_value=? WHERE id=?')->execute([$value,(int)$row['id']]);$this->insertTransaction($participantId,$executionId,$resourceId,$amount,(int)$row['character_class_id']);$this->pdo->commit();return true;}catch(\Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw$e;} }

    public function parseCosts(?string $costs,?string $resourceText=null,?string $classId=null): array
    { $text=trim((string)$costs);if($text==='')$text=trim((string)$resourceText);$out=[];if($text==='')return$out;foreach($this->definitionsByResource($classId) as $def){$name=preg_quote((string)$def['name'],'/');if(preg_match('/(\d+(?:[.,]\d+)?)\s+'.$name.'/iu',$text,$m))$out[]=['resource_id'=>$def['resource_id'],'class_id'=>$def['class_id'],'name'=>$def['name'],'amount'=>(float)str_replace(',','.',$m[1])];}return$out; }
    public function parseGains(?string $text,?string $classId=null): array
    { $text=trim((string)$text);$out=[];if($text==='')return$out;foreach($this->definitionsByResource($classId) as $def){$name=preg_quote((string)$def['name'],'/');if(preg_match('/(?:erzeugt|generiert|gewinn(?:t|e)?|erh(?:ä|a)lt|bekomm(?:t|e)?)\b[^.;\n]{0,80}?(\d+(?:[.,]\d+)?)\s+'.$name.'/iu',$text,$m))$out[]=['resource_id'=>$def['resource_id'],'class_id'=>$def['class_id'],'name'=>$def['name'],'amount'=>(float)str_replace(',','.',$m[1])];}return$out; }

    public function resolveMaximum(array $definition,int $level): ?float
    { $formula=(string)($definition['maximum_formula']??'');if($formula===''){$raw=json_decode((string)($definition['raw_json']??''),true)?:[];$formula=(string)($raw['maximum']??'');}if($formula==='')return null;if(preg_match('/`([^`]+)`/u',$formula,$m))$formula=$m[1];$formula=str_replace(['×','−','–','—'],['*','-','-','-'],$formula);$formula=preg_replace('/[A-Za-zÄÖÜäöüß_-]+-Stufe/u','Stufe',$formula)??$formula;$result=(new FormulaEngine())->evaluate($formula,['variables'=>['Stufe'=>$level]]);return$result['supported']&&$result['value']!==null?(float)$result['value']:$this->tableMaximum($definition,$level); }
    private function tableMaximum(array $definition,int $level): ?float { $raw=json_decode((string)($definition['raw_json']??''),true)?:[];foreach(($raw['tables']??[]) as $table)foreach(($table['rows']??[]) as $row){if(count($row)<2)continue;$range=(string)$row[0];if(preg_match('/^(\d+)\s*[–-]\s*(\d+)$/u',$range,$m)&&$level>=(int)$m[1]&&$level<=(int)$m[2])return(float)str_replace(',','.',$row[1]);if((string)$level===trim($range)&&is_numeric($row[1]))return(float)$row[1];}return null; }
    private function resolveStart(array $definition,?float $max): float { $text=(string)($definition['start_value']??'');if($max!==null&&preg_match('/maximum|höchstwert|vollständig/iu',$text))return$max;if(preg_match('/\b(\d+(?:[.,]\d+)?)\b/u',$text,$m))return$this->clamp((float)str_replace(',','.',$m[1]),$max);return$max??0.0; }
    private function clamp(float $value,mixed $max): float { $value=max(0,$value);return$max!==null&&$max!==''?min($value,(float)$max):$value; }
    private function currentForClass(int $classId,string $resourceId,?float $max): float { $s=$this->pdo->prepare('SELECT current_value FROM character_class_resources WHERE character_class_id=? AND class_resource_id=?');$s->execute([$classId,$resourceId]);$v=$s->fetchColumn();return$v===false?$this->clamp(0,$max):$this->clamp((float)$v,$max); }
    private function definitionsForClass(string $classId,int $level): array { $s=$this->pdo->prepare('SELECT * FROM class_resources WHERE class_id=?');$s->execute([$classId]);$out=[];foreach($s->fetchAll() as $row){$row['class_id']=$classId;$row['class_level']=$level;$row['maximum']=$this->resolveMaximum($row,$level);$out[]=$row;}return$out; }
    private function definitionsByResource(?string $classId=null): array { try{$sql='SELECT resource_id,name,class_id FROM class_resources';$args=[];if($classId!==null&&$classId!==''){$sql.=' WHERE class_id=?';$args[]=$classId;}$s=$this->pdo->prepare($sql);$s->execute($args);return$s->fetchAll();}catch(\Throwable){return[];} }
    private function characterResourceCandidates(int $characterId,string $resourceId,?string $classId): array { $sql='SELECT cc.id character_class_id,cc.class_id,cc.class_level,cr.* FROM character_classes cc JOIN class_resources cr ON cr.class_id=cc.class_id AND cr.resource_id=? WHERE cc.character_id=?';$args=[$resourceId,$characterId];if($classId!==null&&$classId!==''){$sql.=' AND cc.class_id=?';$args[]=$classId;}$s=$this->pdo->prepare($sql);$s->execute($args);return$s->fetchAll(); }
    private function findCombatResource(int $participantId,string $resourceId,?string $classId=null,?int $characterClassId=null): array { $this->reconcileCombatParticipantResources($participantId);$sql="SELECT cpr.*,cr.name,cr.class_id,cc.class_level FROM combat_participant_resources cpr JOIN combat_participants cp ON cp.id=cpr.combat_participant_id JOIN character_classes cc ON cc.id=cpr.character_class_id AND cc.character_id=cp.reference_id JOIN class_resources cr ON cr.class_id=cc.class_id AND cr.resource_id=cpr.class_resource_id WHERE cpr.combat_participant_id=? AND cpr.class_resource_id=?";$args=[$participantId,$resourceId];if($classId!==null&&$classId!==''){$sql.=' AND cc.class_id=?';$args[]=$classId;}if($characterClassId!==null){$sql.=' AND cpr.character_class_id=?';$args[]=$characterClassId;}$s=$this->pdo->prepare($sql);$s->execute($args);$rows=$s->fetchAll();if(count($rows)!==1){$name=$rows[0]['name']??$resourceId;if(count($rows)>1)throw new RuntimeException("Kampfressource '{$name}' ist ohne Klassenbezug nicht eindeutig.");throw new RuntimeException("Kampfressource '{$name}' ist für diese Klasseninstanz im Kampf nicht verfügbar.");}return$rows[0]; }
    private function insertTransaction(int $participantId,string $executionId,string $resourceId,float $delta,int $characterClassId): void { try{$this->pdo->prepare('INSERT INTO combat_resource_transactions (combat_participant_id,execution_id,character_class_id,class_resource_id,delta) VALUES (?,?,?,?,?)')->execute([$participantId,$executionId,$characterClassId,$resourceId,$delta]);}catch(\Throwable){$this->pdo->prepare('INSERT INTO combat_resource_transactions (combat_participant_id,execution_id,class_resource_id,delta) VALUES (?,?,?,?)')->execute([$participantId,$executionId,$resourceId,$delta]);} }
    private function ensureSchema(): void
    {
        $mysql=$this->pdo->getAttribute(PDO::ATTR_DRIVER_NAME)==='mysql';$id=$mysql?'BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY':'INTEGER PRIMARY KEY AUTOINCREMENT';
        try{$this->pdo->exec("CREATE TABLE IF NOT EXISTS class_resources (class_id VARCHAR(120) NOT NULL,resource_id VARCHAR(120) NOT NULL,name VARCHAR(190) NOT NULL,form TEXT NULL,maximum_formula TEXT NULL,start_value TEXT NULL,base_generation TEXT NULL,generation TEXT NULL,consumption TEXT NULL,relief TEXT NULL,persistence TEXT NULL,recovery TEXT NULL,stacking TEXT NULL,transfer TEXT NULL,loss_decay TEXT NULL,visibility TEXT NULL,multiclass_boundary TEXT NULL,base_function TEXT NULL,rounding TEXT NULL,source_file VARCHAR(255) NULL,source_hash VARCHAR(64) NULL,raw_json TEXT NOT NULL,PRIMARY KEY(class_id,resource_id))");}catch(\Throwable){}
        try{$this->pdo->exec("CREATE TABLE IF NOT EXISTS character_class_resources (id {$id},character_class_id INTEGER NOT NULL,class_resource_id VARCHAR(120) NOT NULL,current_value DECIMAL(12,2) NOT NULL DEFAULT 0,created_at DATETIME DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,UNIQUE(character_class_id,class_resource_id))");}catch(\Throwable){}
        try{$this->pdo->exec("CREATE TABLE IF NOT EXISTS combat_participant_resources (id {$id},combat_participant_id INTEGER NOT NULL,character_class_id INTEGER NULL,class_resource_id VARCHAR(120) NOT NULL,current_value DECIMAL(12,2) NOT NULL DEFAULT 0,max_value_snapshot DECIMAL(12,2) NULL,created_at DATETIME DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,UNIQUE(combat_participant_id,character_class_id,class_resource_id))");}catch(\Throwable){}
        try{$this->pdo->exec("CREATE TABLE IF NOT EXISTS combat_resource_transactions (id {$id},combat_participant_id INTEGER NOT NULL,execution_id VARCHAR(190) NOT NULL,character_class_id INTEGER NULL,class_resource_id VARCHAR(120) NOT NULL,delta DECIMAL(12,2) NOT NULL,created_at DATETIME DEFAULT CURRENT_TIMESTAMP,UNIQUE(combat_participant_id,execution_id,class_resource_id))");}catch(\Throwable){}
        foreach(['form','maximum_formula','start_value','base_generation','generation','consumption','relief','persistence','recovery','stacking','transfer','loss_decay','visibility','multiclass_boundary','base_function','rounding','source_file','source_hash'] as $column){try{$this->pdo->query("SELECT {$column} FROM class_resources LIMIT 1");}catch(\Throwable){try{$this->pdo->exec("ALTER TABLE class_resources ADD COLUMN {$column} TEXT NULL");}catch(\Throwable){}}}
        try{$this->pdo->query('SELECT character_class_id FROM combat_resource_transactions LIMIT 1');}catch(\Throwable){try{$this->pdo->exec($mysql?'ALTER TABLE combat_resource_transactions ADD COLUMN character_class_id BIGINT UNSIGNED NULL AFTER execution_id':'ALTER TABLE combat_resource_transactions ADD COLUMN character_class_id INTEGER NULL');}catch(\Throwable){}}
        if($mysql){try{$this->pdo->exec('ALTER TABLE combat_resource_transactions MODIFY character_class_id BIGINT UNSIGNED NULL');}catch(\Throwable){}}
        $this->migrateResourceKeys();
    }
    private function migrateResourceKeys(): void
    { if($this->pdo->getAttribute(PDO::ATTR_DRIVER_NAME)!=='mysql')return;foreach(['fk_character_resource_definition','fk_participant_resource_definition'] as $fk){foreach(['character_class_resources','combat_participant_resources'] as $table){try{$this->pdo->exec("ALTER TABLE {$table} DROP FOREIGN KEY {$fk}");}catch(\Throwable){}}}try{$this->pdo->exec('ALTER TABLE class_resources DROP PRIMARY KEY, ADD PRIMARY KEY(class_id,resource_id)');}catch(\Throwable){}try{$this->pdo->exec('DROP INDEX uq_class_resource_id ON class_resources');}catch(\Throwable){}try{$this->pdo->exec('ALTER TABLE combat_participant_resources DROP INDEX uq_participant_resource, ADD UNIQUE KEY uq_participant_resource (combat_participant_id,character_class_id,class_resource_id)');}catch(\Throwable){}try{$this->pdo->exec('ALTER TABLE combat_resource_transactions DROP INDEX uq_resource_execution, ADD UNIQUE KEY uq_resource_execution (combat_participant_id,execution_id,character_class_id,class_resource_id)');}catch(\Throwable){}}
}
