<?php
declare(strict_types=1);

require dirname(__DIR__) . '/app/bootstrap.php';

use Aetherfall\Repositories\CharacterRepository;
use Aetherfall\Repositories\WeaponRepository;
use Aetherfall\Services\CharacterValidator;
use Aetherfall\Services\CharacterWeaponService;
use Aetherfall\Services\CharacterEquipmentService;
use Aetherfall\Services\EncounterService;
use Aetherfall\Support\Database;

$pdo=Database::connection(); $characters=new CharacterRepository($pdo); $encounters=new EncounterService($pdo); $characterId=null; $encounterId=null;
try {
    $ability=(string)$pdo->query("SELECT id FROM abilities WHERE class_id='taktbrecher' AND unlock_level=1 ORDER BY number LIMIT 1")->fetchColumn();
    $spell=(string)$pdo->query('SELECT id FROM spells ORDER BY id LIMIT 1')->fetchColumn();
    $data=['name'=>'__Codex Smoke Held__','player_name'=>'Test','class_id'=>'taktbrecher','level'=>1,'max_hp'=>999999,'current_hp'=>100,'critical_damage_percent'=>50,'attributes'=>array_map(static fn($c)=>['code'=>$c,'value'=>10,'modifier'=>99,'bonus'=>0],CharacterValidator::ATTRIBUTE_CODES),'ability_ids'=>[$ability],'spell_ids'=>[$spell]];
    $characterId=$characters->save($data); $weaponRepo=new WeaponRepository($pdo); $weaponService=new CharacterWeaponService($pdo,$weaponRepo); $weaponId=(string)$pdo->query('SELECT id FROM weapons ORDER BY id LIMIT 1')->fetchColumn(); $secondWeaponId=(string)$pdo->query('SELECT id FROM weapons WHERE id<>'.$pdo->quote($weaponId).' ORDER BY id LIMIT 1')->fetchColumn();
    $weaponService->setSlot($characterId,'hand_1',$weaponId); $weaponService->setSlot($characterId,'hand_2',$secondWeaponId); $weaponService->setSlot($characterId,'hand_1',$secondWeaponId); $weaponService->clearSlot($characterId,'hand_2');
    $equipment=new CharacterEquipmentService($pdo);$armorIds=[];foreach(CharacterEquipmentService::ARMOR_SLOTS as $slot){$q=$pdo->prepare('SELECT id FROM armors WHERE armor_slot=? ORDER BY id LIMIT 1');$q->execute([$slot]);$armorIds[$slot]=(string)$q->fetchColumn();if($armorIds[$slot]==='')throw new RuntimeException('Rüstungsslot fehlt: '.$slot);$equipment->setArmorSlot($characterId,$slot,$armorIds[$slot]);}$focusId=(string)$pdo->query('SELECT id FROM magic_foci ORDER BY id LIMIT 1')->fetchColumn();$equipment->setMagicFocus($characterId,$focusId);$loaded=$characters->find($characterId); if(count($loaded['attributes'])!==11||count($loaded['abilities'])!==1||count($loaded['spells'])!==1)throw new RuntimeException('Character-Relationen unvollständig.'); if(($loaded['weapons']['hand_1']['id']??null)!==$secondWeaponId||$loaded['weapons']['hand_2']!==null)throw new RuntimeException('Waffenslots wurden nicht geladen oder ersetzt/geleert.'); if(count(array_filter($loaded['armor_slots']))!==5||($loaded['magic_focus']['id']??null)!==$focusId)throw new RuntimeException('Rüstung oder Magiefokus wurde nicht geladen.');$wrongSlot=false;try{$equipment->setArmorSlot($characterId,'head',$armorIds['chest']);}catch(RuntimeException){$wrongSlot=true;}if(!$wrongSlot)throw new RuntimeException('Falscher Rüstungsslot wurde akzeptiert.');$shieldId=(string)$pdo->query("SELECT id FROM armors WHERE item_kind='shield' LIMIT 1")->fetchColumn();$shieldRejected=false;try{$equipment->setArmorSlot($characterId,'hands',$shieldId);}catch(RuntimeException){$shieldRejected=true;}if(!$shieldRejected)throw new RuntimeException('Schild wurde als Rüstung akzeptiert.');$equipment->clearArmorSlot($characterId,'hands');$equipment->clearMagicFocus($characterId);$loaded=$characters->find($characterId);if($loaded['armor_slots']['hands']!==null||$loaded['magic_focus']!==null)throw new RuntimeException('Ausrüstung konnte nicht geleert werden.'); if((int)$loaded['max_hp']!==110)throw new RuntimeException('Serverseitige Max-LP-Berechnung wurde nicht verwendet.'); foreach($loaded['attributes']as$attribute)if((int)$attribute['modifier']!==0)throw new RuntimeException('Client-Modifier wurde nicht ignoriert.'); if(count($loaded['resources'])!==1||$loaded['resources'][0]['resource_id']!=='kampfspannung')throw new RuntimeException('Klassenressource wurde nicht initialisiert.');
    $encounterId=$encounters->create('__Codex Smoke Encounter__'); $encounters->addParticipant($encounterId,['participant_type'=>'character','reference_id'=>$characterId,'selected_level'=>99,'initiative'=>18]); $encounters->addParticipant($encounterId,['participant_type'=>'creature','reference_id'=>'grabhund','selected_level'=>1,'initiative'=>16]); $encounters->addParticipant($encounterId,['participant_type'=>'boss','reference_id'=>'omega-omega-aionios','selected_level'=>1,'initiative'=>12]);
    $fight=$encounters->find($encounterId); if(count($fight['participants'])!==3)throw new RuntimeException('Teilnehmer wurden nicht vollständig geladen.'); $characterParticipant=array_values(array_filter($fight['participants'],static fn($participant)=>$participant['participant_type']==='character'))[0]??null; if(!$characterParticipant||(int)$characterParticipant['selected_level']!==1||(int)($characterParticipant['details']['level']??0)!==1)throw new RuntimeException('Charakterstufe wurde nicht autoritativ vom Charakterbogen übernommen.'); if((float)($characterParticipant['details']['critical_damage_percent']??-1)!==50.0)throw new RuntimeException('Kritischer Schaden fehlt im Charakter-Kontext.'); if(count($characterParticipant['content'])<4)throw new RuntimeException('Klassenaktionen, Fähigkeiten und Zauber wurden im Combat Tracker nicht geladen.'); if(count($characterParticipant['resources'])!==1||$characterParticipant['resources'][0]['class_resource_id']!=='kampfspannung')throw new RuntimeException('Combat-Ressourcensnapshot fehlt.');
    $creatureParticipant=array_values(array_filter($fight['participants'],static fn($participant)=>$participant['participant_type']==='creature'))[0]??null; if(!$creatureParticipant||!isset($creatureParticipant['details']['critical_damage_percent']))throw new RuntimeException('Kritischer Schaden fehlt im Kreaturen-Kontext.');
    $pdo->prepare('UPDATE characters SET level=2 WHERE id=?')->execute([$characterId]); $refreshed=$encounters->find($encounterId); $refreshedCharacter=array_values(array_filter($refreshed['participants'],static fn($participant)=>$participant['participant_type']==='character'))[0]??null; if((int)($refreshedCharacter['selected_level']??0)!==2)throw new RuntimeException('Eine geänderte Charakterbogen-Stufe wurde nicht in den Combat Tracker übernommen.');
    $target=$fight['participants'][1]; $criticalCalculation=['damage'=>['normal_damage'=>5,'critical_applied'=>true,'critical_damage_percent'=>40,'critical_bonus'=>2,'damage_after_critical'=>7,'value'=>7]]; $result=$encounters->applyEffect($encounterId,['target_participant_id'=>$target['id'],'participant_id'=>$fight['participants'][0]['id'],'amount'=>7,'mode'=>'damage','calculation'=>$criticalCalculation]); if($result['after']!==$result['before']-7)throw new RuntimeException('HP-Schaden falsch.'); if(!str_contains($result['message'],'kritisch')||!str_contains($result['message'],'Krit-Bonus +2'))throw new RuntimeException('Kritischer Treffer fehlt im Combat Log.');
    $encounters->moveTurn($encounterId,1); $encounters->moveTurn($encounterId,-1); echo "[OK] MariaDB-Smoke: Character CRUD, Ressourcen, Class Actions, Relationen, Charakter/Kreatur/Boss, Initiative, HP und Log.\n";
} finally { if($encounterId)$pdo->prepare('DELETE FROM combat_encounters WHERE id=?')->execute([$encounterId]); if($characterId)$characters->delete($characterId); }
