<!doctype html>
<html lang="de">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Ätherfall DM-Tool</title>
  <link rel="stylesheet" href="assets/css/app.css?v=20261005-responsive-v2">
  <link rel="stylesheet" href="assets/css/character-calculations.css">
</head>
<body class="app-shell">
<header class="topbar"><button class="brand" data-nav="home">ÄTHERFALL <span>DM-TOOL</span></button><nav><button data-nav="combat">Combat Tracker</button><button data-nav="characters">Charaktere</button></nav></header>
<main>
  <div id="notice" class="notice hidden"></div>
  <section id="page-home" class="page active">
    <div class="hero"><p class="eyebrow">Lokales Spielleiter-Cockpit</p><h1>Alles im Blick.<br><em>Der Tisch bleibt analog.</em></h1><p>Regelwerkdaten, Charaktere und Kämpfe – schnell, nachvollziehbar und ohne automatische Spielerwürfe.</p></div>
    <div class="launch-grid"><button class="launch-card" data-nav="combat"><span class="sigil">⚔</span><strong>Combat Tracker</strong><small>Initiative, LP, Aktionen und Kampfprotokoll</small></button><button class="launch-card" data-nav="characters"><span class="sigil">◈</span><strong>Charaktere</strong><small>Reduzierte DM-Datensätze und Regelverknüpfungen</small></button></div>
    <div id="stats" class="stats"></div>
  </section>

  <section id="page-characters" class="page">
    <div class="section-head"><div><p class="eyebrow">Verwaltung</p><h2>Charaktere</h2></div><button class="primary" id="new-character">+ Charakter erstellen</button></div>
    <div id="character-list" class="card-list"></div>
    <form id="character-form" class="panel hidden">
      <div class="section-head"><h3 id="character-form-title">Charakter erstellen</h3><button type="button" class="ghost" id="close-character">Schließen</button></div>
      <input type="hidden" name="id"><div class="form-grid four"><label>Name<input name="name" maxlength="190" required></label><label>Spieler<input name="player_name" required></label><label>Klasse<select name="class_id" required></select></label><label>Stufe<input name="level" type="number" min="1" value="1" required></label><label>Zusatzname / Beiname<input name="nickname" maxlength="190" placeholder="z. B. der Unbeugsame"></label></div>
      <div id="class-adjustments" class="class-note"></div>
      <h4>Attribute <small>Wert und Bonus werden manuell gepflegt; der Modifikator ist automatisch.</small></h4><div id="attribute-grid" class="attributes"></div>
      <div class="form-grid three"><label>Maximale LP · automatisch<input name="max_hp" type="number" value="110" readonly></label><label>Aktuelle LP<input name="current_hp" type="number" inputmode="numeric" min="0" step="1" value="110"></label><label>Kritischer Schaden %<input name="critical_damage_percent" type="number" min="0" step="0.01" value="0" required></label></div>
      <div id="hp-breakdown" class="hp-breakdown">Klasse wählen, um Max LP zu berechnen.</div>
      <section id="character-resources" class="character-resources hidden"><h4>Klassenressourcen</h4><div id="character-resource-list"></div><h4>Klassenaktionen</h4><div id="character-class-actions"></div></section>
      <div class="split"><div><h4>Fähigkeiten der Klasse</h4><input id="ability-search" placeholder="Fähigkeit suchen …"><div id="ability-options" class="ability-options-grid"></div></div><div><h4>Zauber</h4><div class="filters"><input id="spell-search" placeholder="Zauber suchen …"><select id="spell-element"><option value="">Alle Elemente</option></select><select id="spell-grade"><option value="">Alle Grade</option></select></div><div id="spell-options" class="options"></div></div></div>
      <section class="character-weapons"><div class="section-head"><h4>Waffen</h4><small>Optional · nur zur Charakterverwaltung</small></div><div id="weapon-slots" class="weapon-slots"></div></section>
      <section class="character-equipment"><div class="section-head"><h4>Ausrüstung</h4><small>Rüstung und Magiefokus · nur zur Charakterverwaltung</small></div><div id="armor-slots" class="armor-slots"></div><div id="magic-focus-slot" class="magic-focus-slot"></div></section>
      <section id="character-defense-summary" class="character-defense-summary hidden"><div class="section-head"><h4>Verteidigung</h4><small>Automatisch aus der ausgerüsteten Rüstung berechnet</small></div><div id="character-defense-values" class="character-defense-values"></div></section>
      <div class="actions"><button class="primary" type="submit">Charakter speichern</button></div>
    </form>
  </section>

  <section id="page-combat" class="page">
    <div class="section-head"><div><p class="eyebrow">Sitzungsmodus</p><h2>Combat Tracker</h2></div><button class="primary" id="new-encounter">+ Kampf erstellen</button></div>
    <div id="encounter-list" class="card-list"></div>
    <div id="encounter-detail" class="hidden" data-mobile-view="combat">
      <nav class="combat-mobile-tabs" aria-label="Combat-Bereiche"><button type="button" data-combat-view="participants">Teilnehmer</button><button type="button" class="active" data-combat-view="combat">Kampf</button><button type="button" data-combat-view="log">Protokoll</button></nav>
      <div class="combat-toolbar"><button class="ghost" id="back-encounters">← Kämpfe</button><h3 id="encounter-title"></h3><div class="round">Runde <strong id="round-number">1</strong></div><button id="previous-turn">← Vorheriger Zug</button><button class="primary" id="next-turn">Nächster Zug →</button></div>
      <div class="combat-layout"><aside class="initiative-sidebar"><div class="sidebar-heading"><h4>Initiative</h4><span>Runde <strong id="sidebar-round-number">1</strong></span></div><div id="initiative-list" class="initiative"></div><button class="primary add-participant-button" id="open-participant-modal" type="button">+ Teilnehmer</button></aside>
      <section class="combat-main"><div id="active-card" class="panel"></div><button class="primary combat-calculator-open hidden" id="open-combat-calculator" type="button">Aktion / Angriff öffnen</button><div id="combat-calculator-modal" class="modal hidden" aria-hidden="true"><div class="modal-card combat-calculator-modal-card" role="dialog" aria-modal="true" aria-labelledby="combat-calculator-title"><button class="modal-close" id="close-combat-calculator" type="button" aria-label="Schließen">×</button><div class="panel calculator"><h4 id="combat-calculator-title">Combat Calculator <small id="calculator-actor"></small></h4><label id="combat-source-legacy-field">Aktion / Fähigkeit<select id="combat-source"></select></label><label id="weapon-selection-field" class="hidden">Waffe<select id="combat-weapon"></select></label><label id="combat-target-field">Ziel<select id="combat-target"></select></label><label id="attack-formula-field">Trefferformel<output id="combat-attack-formula" class="formula-output">—</output></label><div id="hit-roll-fields" class="form-grid two hidden"><label id="hit-roll-field">Trefferwürfel<input id="hit-roll" type="number" min="0" step="1" inputmode="numeric"></label><label id="target-roll-field">Ausweichwürfel des Ziels<input id="target-roll" type="number" min="0" step="1" inputmode="numeric"></label></div><label id="combat-damage-formula-field">Schadensformel<output id="combat-formula" class="formula-output">—</output></label><div id="dice-inputs"></div><div id="combat-meta-fields" class="form-grid two"><label id="magic-attribute-field">Magieattribut<select id="magic-attribute"><option value="">Nicht festgelegt</option></select></label><div id="magic-focus-context" class="magic-focus-context hidden" aria-live="polite"></div><div id="critical-control" class="crit-control"><label class="crit-check" for="critical"><input id="critical" type="checkbox"><span class="crit-check-box" aria-hidden="true"></span><span class="crit-check-label">Kritischer Treffer</span></label><span id="critical-hint" class="crit-badge" aria-live="polite"></span></div></div><p id="automatic-target-hint" class="field-hint">Treffer- und Schadenswürfel werden physisch gewürfelt und hier als Summen eingetragen.</p><div id="manual-values"></div><div id="calculation-result"></div><div id="calculator-action-bar" class="calculator-action-bar"><button class="primary" id="calculate" type="button">Berechnen</button><div class="apply-row hidden" id="apply-row"><button id="apply-damage" type="button">Schaden anwenden</button><button id="apply-healing" type="button">Heilung anwenden</button></div></div></div></div></div><div class="panel"><h4>Kampfprotokoll</h4><div id="combat-log" class="log"></div></div></section></div>
    </div>
  </section>
</main>
<label id="weapon-profile-selection-field" class="hidden">Führungsart / Waffenprofil<select id="combat-weapon-profile"></select></label>
<div id="participant-modal" class="modal hidden" aria-hidden="true"><div class="modal-card" role="dialog" aria-modal="true" aria-labelledby="participant-modal-title"><button class="modal-close" id="close-participant-modal" type="button" aria-label="Schließen">×</button><h3 id="participant-modal-title">Teilnehmer hinzufügen</h3><form id="participant-form"><div class="form-grid two"><label>Teilnehmertyp<select name="participant_type"><option value="character">Charakter</option><option value="creature">Kreatur</option><option value="boss">Boss</option></select></label><label>Auswahl<select name="reference_id"></select></label><label>Stufe<select name="selected_level"></select></label><label>Initiative-Wurf (W20)<input name="initiative" type="number" min="1" max="20" step="1" value="" inputmode="numeric" required></label><label id="boss-hp-multiplier-field" class="hidden">Boss-LP-Multiplikator<input name="boss_hp_multiplier" type="number" min="1" step="1" value="1" inputmode="numeric"><small>Manuell: Profil-LP × dieser Wert</small></label></div><p class="field-hint">Gesamtinitiative = W20 + Beweglichkeitsmodifikator + Beweglichkeitsbonus.</p><p id="participant-empty-hint" class="field-hint hidden"></p><p id="participant-error" class="field-hint hidden" role="alert"></p><div class="modal-actions"><button class="ghost" id="cancel-participant-modal" type="button">Abbrechen</button><button class="primary" id="participant-submit" type="submit">Hinzufügen</button></div></form></div></div>
<div id="weapon-modal" class="modal hidden" aria-hidden="true"><div class="modal-card weapon-modal-card" role="dialog" aria-modal="true" aria-labelledby="weapon-modal-title"><button class="modal-close" id="close-weapon-modal" type="button" aria-label="Schließen">×</button><h3 id="weapon-modal-title">Waffe wählen</h3><div class="filters weapon-filters"><input id="weapon-search" placeholder="Waffe suchen …"><select id="weapon-quality"><option value="">Alle Qualitätsstufen</option></select><select id="weapon-category"><option value="">Alle Kategorien</option></select><select id="weapon-magical"><option value="">Magisch: alle</option><option value="1">Magisch</option><option value="0">Nicht magisch</option></select></div><div id="weapon-options" class="weapon-options"></div></div></div>
<div id="armor-modal" class="modal hidden" aria-hidden="true"><div class="modal-card equipment-modal-card" role="dialog" aria-modal="true" aria-labelledby="armor-modal-title"><button class="modal-close" id="close-armor-modal" type="button" aria-label="Schließen">×</button><h3 id="armor-modal-title">Rüstung wählen</h3><p id="armor-modal-slot" class="field-hint"></p><div class="filters equipment-filters"><input id="armor-search" placeholder="Rüstung suchen …"><select id="armor-quality"><option value="">Alle Qualitätsstufen</option></select><select id="armor-archetype"><option value="">Alle Rüstungsarten</option></select><select id="armor-item-level"><option value="">Alle Itemstufen</option></select></div><div id="armor-options" class="equipment-options"></div></div></div>
<div id="magic-focus-modal" class="modal hidden" aria-hidden="true"><div class="modal-card equipment-modal-card" role="dialog" aria-modal="true" aria-labelledby="magic-focus-modal-title"><button class="modal-close" id="close-magic-focus-modal" type="button" aria-label="Schließen">×</button><h3 id="magic-focus-modal-title">Magiefokus wählen</h3><div class="filters equipment-filters"><input id="magic-focus-search" placeholder="Magiefokus suchen …"><select id="magic-focus-quality"><option value="">Alle Qualitätsstufen</option></select><select id="magic-focus-category"><option value="">Alle Kategorien</option></select><select id="magic-focus-elemental"><option value="">Alle Foki</option><option value="1">Elementarfoki</option><option value="0">Nicht elementar</option></select></div><div id="magic-focus-options" class="equipment-options"></div></div></div>
  <script src="assets/js/app.js?v=20261005-nickname-v1"></script>
</body></html>

